In [2]:
import myfunctions as mf
from skimage.io import imshow
import time as clock
import numpy as np
import napari 
from tqdm import tqdm
from numpy.lib.format import open_memmap
import os

In [4]:
OS = 'Windows'
exp = mf.exp_list()[0]
end_time = 220
skip180 = True

# start_time = mf.exp_start_time()[mf.exp_list().index(exp)]
# time_steps = range(start_time, end_time+1, 2) if skip180 else range(start_time, end_time+1)
# volume = mf.load_volume(exp=exp, time=start_time, isImage=True, OS=OS)
# volume = open_memmap(mf.volume_path(exp=exp, time=start_time, OS=OS, isImage=True), mode='r', dtype=np.half)
# hypervolume = open_memmap(os.path.join(mf.OS_path(exp, OS), 'hypervolume.npy'), dtype=np.half, mode='w+', shape=(2, volume.shape[0], volume.shape[1], volume.shape[2]))
# print(volume.dtype)
# print(hypervolume.dtype)

hypervolume = open_memmap('hypervolume.npy', dtype=np.ushort, mode='w+', shape=(2, 2, 2))
print(hypervolume)
a = np.array([[1,2],[3,4]], dtype=np.ushort)
hypervolume[0] = a
print(hypervolume)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 2]
  [3 4]]

 [[0 0]
  [0 0]]]


In [10]:
b = [1, 3, 5, 7]
c = range(len(b))
for i in c[:-1][::-1]:
    print(i)

2
1
0
